### ISSUE TITLE
Change name of the config value

### ISSUE THREAD

**Issue by devconcept** [patrickmarabeas/ng-ScrollSpy.js#16]
Hi
I just installed your module with bower in my app an got a weird issue. Suddenly all our tests regarding the configuration of our app were failing. I tracked the issue to your module to line 15 where you got

```
.value('config', {
    'offset': 200,
     'delay': 100
})
```

We also named "config" our factory for the app configuration so we have to rename it to "app.config". Regardless I think "config" this is a far to common name for a provider and you should namespace yours so it doesn't conflict with anyone elses. This is a good practice when building a library and it can save hours of debugging, maybe use "ngScrollSpy.config". The change is minimun and should not require much effort.

**Comment by patrickmarabeas** [comment]
Will update ASAP.

**Comment by patrickmarabeas** [comment]
Patched in [v3.2.2](https://github.com/patrickmarabeas/ng-ScrollSpy.js/releases/tag/v3.2.2).
