### ISSUE TITLE
Not seems to be working

### ISSUE THREAD

**Issue by EugeneFeshchenko** [patrickmarabeas/ng-ScrollSpy.js#9]
Hi,
your demo site http://patrickmarabeas.github.io/ng-ScrollSpy.js/ is not highliting currently scrolled item. And when I installed and set up plugin on my project it fails with error:

Exception
Error: config.throttle is not a function
.link@http://127.0.0.1:8000/static/vendor/ng-ScrollSpy.js/src/ng-ScrollSpy.js:90:54

Am I doing something wrong ?

**Comment by patrickmarabeas** [comment]
Oops! Was linking to dev location of Angular - fixed : )

Issue has been fixed in v3.2.1 - a remnant from when the throttle function was included and the setting was simply a bool.

Thanks!
